nav:
- Accueil: 'index.md'
- 'Premiers pas':
    - 'Introduction': 'begin/intro.md'
    - 'Installation': 'begin/installation.md'
    - 'Première simulation': 'begin/first_simulation.md'
- Principe: 'principe/intro.md'
- 'Environnement géographique':
    - 'Introduction': 'envgeo/intro.md'
    - 'Modèle géographique détaillé': 'envgeo/modelgeo.md'
    - "Processus d'intégration": 'envgeo/integration.md'
    - "Tester l'intégration": 'envgeo/integration-test.md'
- 'Générateur de formes':
    - 'Introduction': 'generator/intro.md'
    - 'Principe de fonctionnement du générateur': 'generator/principe.md'
    - "Paramétrer la génération de boîtes": 'generator/custom-generator.md'
    - "Personnaliser la fonction d'optimisation": 'generator/custom-optimisation.md'
    - 'Personnaliser les formes utilisées': 'generator/custom-shape.md'
- 'Définition des contraintes morphologiques':
    - 'Introduction': 'rules/intro.md'
    - 'Principe de fonctionnement du vérificateur': 'rules/predicate.md'
    - 'Formats de règles': 'rules/formats.md'
    - 'Définition de contraintes topologiques': 'rules/topologique.md'
- "Exporter les résultats d'une simulation": 'export.md'
- "Suivre l'évolution d'une simulation": 'visitor/intro.md'
- 'Distribuer avec OpenMole': 'openmole/intro.md'
- 'Futurs développements': 'development.md'
- 'À propos': 'about.md'
- 'Réalisations et bibliographie' : 'bibliographie.md'
theme: readthedocs
site_name: SimPLU3D tutorial
site_url: https://simplu3D.github.io/simplu3D-tutorial
repo_url: https://github.com/SimPLU3D/simplu3D-tutorial
repo_name: GitHub
edit_uri: '?query=root/path/docs/'
site_description: 'Tutorial for SimPLU3D application'
site_author: 'MBrasebin'
copyright: 'IGNF 2018-2019'
lang: fr

markdown_extensions:
    - toc:
        permalink: 
